from pathlib import Path

p = Path('app/app/upload/page.tsx')
s = p.read_text()

s = s.replace('import MenuFotografo from "../MenuFotografo";','import MenuFotografo from "../MenuFotografo";\nimport * as tus from "tus-js-client";',1)

anchor = 'function gerarSlug(texto:string){return texto.toLowerCase().normalize("NFD").replace(/[\\u0300-\\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")}\n'
insert = anchor + 'function endpointTus(){const base=process.env.NEXT_PUBLIC_SUPABASE_URL;if(!base)throw new Error("Supabase não configurado");const ref=new URL(base).hostname.split(".")[0];return `https://${ref}.storage.supabase.co/storage/v1/upload/resumable`}\n'
if anchor not in s: raise SystemExit('slug anchor not found')
s = s.replace(anchor, insert, 1)

old_state = ' const[carregando,setCarregando]=useState(true),[enviando,setEnviando]=useState(false),[mensagem,setMensagem]=useState(""),[erro,setErro]=useState(false),[arquivos,setArquivos]=useState<File[]>([]),[arquivosRejeitados,setArquivosRejeitados]=useState<ArquivoRejeitado[]>([]),[nomeGaleria,setNomeGaleria]=useState(""),[tituloTravado,setTituloTravado]=useState(""),[link,setLink]=useState("");\n const[clientes,setClientes]=useState<Cliente[]>([]),[clienteId,setClienteId]=useState(""),[novoCliente,setNovoCliente]=useState(false),[clienteNome,setClienteNome]=useState(""),[clienteEmail,setClienteEmail]=useState(""),[clienteTelefone,setClienteTelefone]=useState("");'
new_state = ' const[carregando,setCarregando]=useState(true),[enviando,setEnviando]=useState(false),[mensagem,setMensagem]=useState(""),[erro,setErro]=useState(false),[arquivos,setArquivos]=useState<File[]>([]),[arquivosRejeitados,setArquivosRejeitados]=useState<ArquivoRejeitado[]>([]),[nomeGaleria,setNomeGaleria]=useState(""),[tituloTravado,setTituloTravado]=useState(""),[link,setLink]=useState(""),[galeriaDestinoId,setGaleriaDestinoId]=useState<string|null>(galeriaFixa),[galeriaInvalida,setGaleriaInvalida]=useState(false),[progresso,setProgresso]=useState(0),[processadas,setProcessadas]=useState(0),[totalEnvio,setTotalEnvio]=useState(0);\n const[clientes,setClientes]=useState<Cliente[]>([]),[clienteId,setClienteId]=useState(""),[novoCliente,setNovoCliente]=useState(false),[clienteNome,setClienteNome]=useState(""),[clienteEmail,setClienteEmail]=useState(""),[clienteTelefone,setClienteTelefone]=useState("");\n const nomesStorage=useRef<Map<File,string>>(new Map()),progressoBytes=useRef<Map<string,number>>(new Map()),totalBytes=useRef(0);'
if old_state not in s: raise SystemExit('state anchor not found')
s = s.replace(old_state,new_state,1)

old_effect = ' useEffect(()=>{let ativo=true;(async()=>{const{data}=await supabase.auth.getUser();if(!data.user){router.replace("/login");return}const uid=data.user.id;const{data:cs}=await supabase.from("clientes").select("id,nome,email,telefone").eq("user_id",uid).order("nome");const listaClientes=(cs??[]) as Cliente[];if(ativo){setClientes(listaClientes);if(!galeriaFixa&&clienteInicial&&listaClientes.some(c=>c.id===clienteInicial))setClienteId(clienteInicial)}if(galeriaFixa){const{data:g}=await supabase.from("galerias").select("titulo,cliente_id").eq("id",galeriaFixa).eq("user_id",uid).maybeSingle();if(ativo){setTituloTravado(g?.titulo||"Galeria");setClienteId((g?.cliente_id as string|null)??"")}}if(ativo)setCarregando(false)})();return()=>{ativo=false}},[router,supabase,galeriaFixa,clienteInicial]);'
new_effect = ' useEffect(()=>{let ativo=true;(async()=>{const{data}=await supabase.auth.getUser();if(!data.user){router.replace("/login");return}const uid=data.user.id;const{data:cs}=await supabase.from("clientes").select("id,nome,email,telefone").eq("user_id",uid).order("nome");const listaClientes=(cs??[]) as Cliente[];if(ativo){setClientes(listaClientes);if(!galeriaFixa&&clienteInicial&&listaClientes.some(c=>c.id===clienteInicial))setClienteId(clienteInicial)}if(galeriaFixa){const{data:g}=await supabase.from("galerias").select("titulo,cliente_id").eq("id",galeriaFixa).eq("user_id",uid).maybeSingle();if(ativo){if(!g){setGaleriaInvalida(true);setErro(true);setMensagem("Esta galeria não existe ou não pertence à sua conta.")}else{setTituloTravado(g.titulo||"Galeria");setClienteId((g.cliente_id as string|null)??"")}}}if(ativo)setCarregando(false)})();return()=>{ativo=false}},[router,supabase,galeriaFixa,clienteInicial]);\n useEffect(()=>{const sair=(e:BeforeUnloadEvent)=>{if(!enviando)return;e.preventDefault();e.returnValue=""};window.addEventListener("beforeunload",sair);return()=>window.removeEventListener("beforeunload",sair)},[enviando]);'
if old_effect not in s: raise SystemExit('load effect anchor not found')
s = s.replace(old_effect,new_effect,1)

old_select = ' function selecionarArquivos(lista:FileList|null){const selecionados=Array.from(lista??[]),validos:File[]=[],rejeitados:ArquivoRejeitado[]=[];selecionados.forEach((arquivo,i)=>{if(i>=MAX_ARQUIVOS_POR_LOTE){rejeitados.push({nome:arquivo.name,motivo:`limite de ${MAX_ARQUIVOS_POR_LOTE} fotos por lote`});return}const motivo=validarArquivo(arquivo);if(motivo)rejeitados.push({nome:arquivo.name,motivo});else validos.push(arquivo)});setArquivos(validos);setArquivosRejeitados(rejeitados);setMensagem("");setErro(false)}'
new_select = ' function selecionarArquivos(lista:FileList|null){const selecionados=Array.from(lista??[]),validos:File[]=[],rejeitados:ArquivoRejeitado[]=[];selecionados.forEach((arquivo,i)=>{if(i>=MAX_ARQUIVOS_POR_LOTE){rejeitados.push({nome:arquivo.name,motivo:`limite de ${MAX_ARQUIVOS_POR_LOTE} fotos por lote`});return}const motivo=validarArquivo(arquivo);if(motivo)rejeitados.push({nome:arquivo.name,motivo});else validos.push(arquivo)});nomesStorage.current.clear();progressoBytes.current.clear();setProgresso(0);setProcessadas(0);setTotalEnvio(0);setArquivos(validos);setArquivosRejeitados(rejeitados);setMensagem("");setErro(false)}'
if old_select not in s: raise SystemExit('select anchor not found')
s = s.replace(old_select,new_select,1)

start = s.index(' async function enviarFotos(){')
end = s.index('\n async function copiarLink()', start)
new_upload = r''' async function enviarOriginalResumivel(arquivo:File,caminho:string,onProgress:(bytes:number)=>void){
  const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token)throw new Error("Sessão expirada");
  return new Promise<void>((resolve,reject)=>{let terminou=false;const upload=new tus.Upload(arquivo,{endpoint:endpointTus(),retryDelays:[0,1000,3000,5000,10000],headers:{authorization:`Bearer ${session.access_token}`},uploadDataDuringCreation:true,removeFingerprintOnSuccess:true,chunkSize:6*1024*1024,metadata:{bucketName:"fotos",objectName:caminho,contentType:arquivo.type,cacheControl:"3600"},fingerprint:async()=>`fotura-${caminho}-${arquivo.size}-${arquivo.lastModified}`,onProgress:(bytes)=>onProgress(bytes),onError:(e)=>{if(!terminou){terminou=true;reject(e)}},onSuccess:()=>{if(!terminou){terminou=true;resolve()}}});upload.findPreviousUploads().then(prev=>{if(prev.length)upload.resumeFromPreviousUpload(prev[0]);upload.start()}).catch(reject)})
 }
 async function enviarThumb(caminho:string,thumb:Blob){for(let tentativa=0;tentativa<2;tentativa++){const{error}=await supabase.storage.from("fotos").upload(caminho,thumb,{contentType:"image/jpeg",cacheControl:"3600"});if(!error)return true;if(tentativa===0)await new Promise(r=>setTimeout(r,500))}return false}
 async function enviarFotos(){
  setErro(false);setLink("");setMensagem("");if(galeriaInvalida){setErro(true);setMensagem("Não é possível enviar fotos para esta galeria.");return}if(!arquivos.length){setErro(true);setMensagem("Escolha pelo menos uma foto válida.");return}
  const{data:u}=await supabase.auth.getUser();if(!u.user){router.replace("/login");return}const uid=u.user.id,revalidacao=arquivos.map(a=>({arquivo:a,motivo:validarArquivo(a)})),invalidos=revalidacao.filter(x=>x.motivo);if(invalidos.length){setArquivos(revalidacao.filter(x=>!x.motivo).map(x=>x.arquivo));setArquivosRejeitados(prev=>[...prev,...invalidos.map(x=>({nome:x.arquivo.name,motivo:x.motivo!}))]);setErro(true);setMensagem("Algumas fotos deixaram de ser válidas. Revise a seleção antes de enviar.");return}
  let galeriaId=galeriaDestinoId,galeriaCriadaAgora=false,clienteCriadoAgora:string|null=null;
  if(!galeriaId){const t=nomeGaleria.trim();if(!t){setErro(true);setMensagem("Dê um nome pra galeria.");return}const novoNome=novoCliente?clienteNome.trim():"";if(novoCliente&&!novoNome){setErro(true);setMensagem("Informe o nome do novo cliente.");return}const{data:nova,error:e}=await supabase.rpc("criar_galeria_transacional",{p_slug:gerarSlug(t),p_titulo:t,p_cliente_id:novoCliente?null:(clienteId||null),p_cliente_nome:novoCliente?novoNome:null,p_cliente_email:novoCliente?(clienteEmail.trim()||null):null,p_cliente_telefone:novoCliente?(clienteTelefone.trim()||null):null}).single();const registro=nova as {galeria_id:string;cliente_id:string|null}|null;if(e||!registro){setErro(true);setMensagem("Não foi possível criar a galeria.");return}galeriaId=registro.galeria_id;galeriaCriadaAgora=true;clienteCriadoAgora=novoCliente?registro.cliente_id:null;setGaleriaDestinoId(galeriaId);setTituloTravado(t)}
  const lista=[...arquivos];setEnviando(true);setProcessadas(0);setTotalEnvio(lista.length);setProgresso(0);progressoBytes.current.clear();totalBytes.current=lista.reduce((acc,a)=>acc+a.size,0);
  const falhas:File[]=[],thumbFalhas:string[]=[];let enviadas=0,cursor=0,concluidas=0;
  const atualizar=(chave:string,bytes:number)=>{progressoBytes.current.set(chave,bytes);const feito=[...progressoBytes.current.values()].reduce((a,b)=>a+b,0);setProgresso(totalBytes.current?Math.min(100,Math.round(feito/totalBytes.current*100)):0)};
  const worker=async()=>{while(true){const i=cursor++;if(i>=lista.length)return;const arq=lista[i];let nome=nomesStorage.current.get(arq);if(!nome){const limpo=arq.name.replace(/[^a-zA-Z0-9._-]/g,"_");const id=typeof crypto!=="undefined"&&"randomUUID" in crypto?crypto.randomUUID():`${Date.now()}-${i}-${Math.random().toString(36).slice(2)}`;nome=`${id}-${limpo}`;nomesStorage.current.set(arq,nome)}const caminho=`${uid}/${galeriaId}/${nome}`;try{await enviarOriginalResumivel(arq,caminho,b=>atualizar(caminho,b));atualizar(caminho,arq.size);enviadas++;const thumb=await gerarMiniatura(arq);if(thumb&&!await enviarThumb(`${uid}/${galeriaId}/thumbs/${nome}`,thumb))thumbFalhas.push(arq.name)}catch{falhas.push(arq)}finally{concluidas++;setProcessadas(concluidas)}}};
  await Promise.all(Array.from({length:Math.min(3,lista.length)},()=>worker()));
  if(enviadas===0){if(galeriaCriadaAgora&&galeriaId){const{error:rollbackError}=await supabase.rpc("desfazer_galeria_vazia",{p_galeria:galeriaId,p_cliente_id:clienteCriadoAgora});if(!rollbackError){setGaleriaDestinoId(null);setTituloTravado("");nomesStorage.current.clear();setErro(true);setMensagem("Nenhuma foto foi enviada. A galeria vazia foi descartada; tente novamente.");setEnviando(false);return}}setErro(true);setMensagem("Nenhuma foto foi enviada. Os arquivos continuam selecionados para uma nova tentativa.");setEnviando(false);return}
  setLink(`${window.location.origin}/g/${galeriaId}`);setArquivos(falhas);setProgresso(100);setEnviando(false);
  if(falhas.length){setErro(true);const amostra=falhas.slice(0,3).map(f=>f.name).join(", "),restante=falhas.length>3?` e mais ${falhas.length-3}`:"";setMensagem(`${enviadas} foto(s) enviada(s). ${falhas.length} falharam e ficaram prontas para tentar novamente: ${amostra}${restante}.`)}else if(thumbFalhas.length){setErro(false);setMensagem(`${enviadas} foto(s) enviada(s) com sucesso. ${thumbFalhas.length} miniatura(s) não puderam ser geradas; a galeria usará a foto original como fallback.`)}else{setErro(false);setMensagem(`${enviadas} foto(s) enviada(s) com sucesso!`)}
 }'''
s = s[:start] + new_upload + s[end:]

s = s.replace('.up-link{margin-top:20px;padding:16px;background:#0f0f1a;border:1px solid #2a2d40;border-radius:10px}', '.up-progress{margin:14px 0 16px}.up-progress-head{display:flex;justify-content:space-between;gap:12px;font-size:11px;color:#8f93aa;margin-bottom:7px}.up-progress-track{height:7px;border-radius:999px;background:#0d0d19;overflow:hidden;border:1px solid #25283d}.up-progress-fill{height:100%;background:linear-gradient(90deg,#1196fc,#5d0dfa);transition:width .2s ease}.up-link{margin-top:20px;padding:16px;background:#0f0f1a;border:1px solid #2a2d40;border-radius:10px}',1)

s = s.replace('<input className="up-input" value={nomeTravado?tituloTravado:nomeGaleria} onChange={e=>setNomeGaleria(e.target.value)} disabled={nomeTravado}', '<input className="up-input" value={galeriaDestinoId?tituloTravado:nomeGaleria} onChange={e=>setNomeGaleria(e.target.value)} disabled={Boolean(galeriaDestinoId)||enviando}',1)
s = s.replace('{!nomeTravado&&<><div className="up-client-head">', '{!galeriaDestinoId&&<><div className="up-client-head">',1)
s = s.replace('{nomeTravado&&clienteAtual&&<p className="up-note">', '{galeriaDestinoId&&clienteAtual&&<p className="up-note">',1)
s = s.replace('<button type="button" className="up-file" onClick={()=>inputRef.current?.click()}>Escolher fotos</button>', '<button type="button" className="up-file" onClick={()=>inputRef.current?.click()} disabled={enviando||galeriaInvalida}>Escolher fotos</button>',1)
old_button = '<button className="up-enviar" onClick={enviarFotos} disabled={enviando||arquivos.length===0}>{enviando?"Enviando…":nomeTravado?"Enviar fotos":"Criar nova galeria"}</button>'
new_button = '<button className="up-enviar" onClick={enviarFotos} disabled={enviando||arquivos.length===0||galeriaInvalida}>{enviando?`Enviando… ${progresso}%`:galeriaDestinoId?(link?`Tentar novamente ${arquivos.length} foto${arquivos.length===1?"":"s"}`:"Enviar fotos"):"Criar nova galeria"}</button>{enviando&&<div className="up-progress" aria-live="polite"><div className="up-progress-head"><span>{processadas}/{totalEnvio} fotos processadas</span><span>{progresso}%</span></div><div className="up-progress-track"><div className="up-progress-fill" style={{width:`${progresso}%`}}/></div></div>}'
if old_button not in s: raise SystemExit('button anchor not found')
s = s.replace(old_button,new_button,1)

p.write_text(s)
