-- Product/acquisition analytics. The browser never receives direct table access.
create table if not exists public.produto_eventos (
  id bigint generated by default as identity primary key,
  user_id uuid null references auth.users(id) on delete set null,
  evento text not null check (char_length(evento) between 2 and 80),
  rota text null check (rota is null or char_length(rota) <= 180),
  entidade text null check (entidade is null or char_length(entidade) <= 40),
  entidade_id text null check (entidade_id is null or char_length(entidade_id) <= 160),
  sessao_id text null check (sessao_id is null or char_length(sessao_id) <= 100),
  detalhes jsonb not null default '{}'::jsonb,
  criado_em timestamptz not null default now()
);

alter table public.produto_eventos enable row level security;

revoke all on table public.produto_eventos from public, anon, authenticated;
grant select, insert, update, delete on table public.produto_eventos to service_role;
grant usage, select on sequence public.produto_eventos_id_seq to service_role;

create index if not exists produto_eventos_evento_criado_em_idx
  on public.produto_eventos (evento, criado_em desc);
create index if not exists produto_eventos_user_id_criado_em_idx
  on public.produto_eventos (user_id, criado_em desc)
  where user_id is not null;
create index if not exists produto_eventos_sessao_id_criado_em_idx
  on public.produto_eventos (sessao_id, criado_em desc)
  where sessao_id is not null;
