"use client";
import { useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "../../../lib/supabase-client";
import MenuFotografo from "../../MenuFotografo";
const GIB=1024*1024*1024;
type Galeria={id:string;titulo:string;etapa:string;criadoEm:string|null;linkAte:string|null;expirada:boolean;storageLimpo:boolean;bytesTotal:number;arquivosTotal:number;bytesEntrega:number;arquivosEntrega:number};
type Dados={plano:{codigo:string;nome:string};usoBytes:number;limiteGb:number|null;residualBytes:number;galerias:Galeria[]};
function fmt(b:number){if(b<1024*1024)return Math.max(0,b/1024).toFixed(0)+" KB";if(b<GIB)return (b/1024/1024).toFixed(b>=100*1024*1024?0:1)+" MB";return (b/GIB).toFixed(b>=10*GIB?1:2)+" GB"}
export default function ArmazenamentoPage(){
 const router=useRouter(),supabase=useMemo(()=>createClient(),[]);
 const[dados,setDados]=useState<Dados|null>(null),[erro,setErro]=useState(""),[apagando,setApagando]=useState("");
 async function carregar(){setErro("");const{data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token){router.replace("/login");return}const r=await fetch("/api/storage/resumo",{headers:{Authorization:"Bearer "+token},cache:"no-store"});if(!r.ok){setErro("Não foi possível carregar seu armazenamento.");return}setDados(await r.json() as Dados)}
 useEffect(()=>{void carregar()},[]);
 async function excluir(g:Galeria){if(apagando)return;if(!window.confirm("Excluir a galeria \""+g.titulo+"\" e liberar o espaço ocupado? Esta ação não pode ser desfeita."))return;const{data}=await supabase.auth.getSession();const token=data.session?.access_token;if(!token)return;setApagando(g.id);const r=await fetch("/api/galeria/excluir",{method:"DELETE",headers:{"Content-Type":"application/json",Authorization:"Bearer "+token},body:JSON.stringify({galeria:g.id})});const d=await r.json().catch(()=>({}));setApagando("");if(!r.ok){setErro(d.error||"Não foi possível excluir a galeria.");return}await carregar()}
 const limiteBytes=dados?.limiteGb==null?null:dados.limiteGb*GIB,pct=limiteBytes?Math.min(100,Math.round(((dados?.usoBytes??0)/limiteBytes)*100)):0;
 const ativas=(dados?.galerias??[]).filter(g=>g.bytesTotal>0).length;
 return <div className="mf-shift st"><MenuFotografo/><style>{".st{min-height:100vh;background:linear-gradient(180deg,#F0EDF7,#ECE8F4);color:#21253A}.wrap{max-width:1120px;margin:auto;padding:42px 40px 100px}.ey{font-size:10px;letter-spacing:1.8px;color:#737cae;font-weight:800}.st h1{font-size:31px;margin:7px 0 5px}.sub{margin:0;color:#73758D;font-size:12px;line-height:1.6}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:24px 0}.card,.panel{background:linear-gradient(180deg,#FAF8FD,#F3EFF9);border:1px solid #DCD6EE;border-radius:15px}.card{padding:18px}.card strong{display:block;font-size:25px}.card span{display:block;margin-top:6px;color:#73758D;font-size:10px}.meter{margin:0 0 22px;padding:18px}.meter-head{display:flex;justify-content:space-between;gap:16px;margin-bottom:9px;font-size:11px}.track{height:8px;background:#E5DFEE;border-radius:999px;overflow:hidden}.track i{display:block;height:100%;background:linear-gradient(90deg,#1196fc,#5d0dfa);border-radius:inherit}.actions{display:flex;gap:8px;margin-top:12px}.btn{min-height:38px;padding:0 12px;border:1px solid #CFC6E6;border-radius:9px;background:#FAF8FD;color:#514780;font:700 10px inherit;cursor:pointer}.btn.primary{border:0;color:white;background:linear-gradient(90deg,#1196fc,#5d0dfa)}.table-wrap{overflow:auto;border:1px solid #DCD6EE;border-radius:15px;background:#FAF8FD}.table{width:100%;min-width:900px;border-collapse:collapse}.table th,.table td{text-align:left;padding:12px 13px;border-bottom:1px solid #E5DFEE;font-size:10.5px}.table th{color:#73758D;background:#FAF8FD}.name{font-weight:750;color:#21253A}.muted{color:#7E8399;font-size:9px;margin-top:3px}.pill{display:inline-flex;padding:4px 7px;border:1px solid #D7D0E7;border-radius:999px;background:#F3EFF9;font-size:9px}.pill.done{color:#3F7C5B}.pill.warn{color:#9A6D10}.err,.note{margin:12px 0;padding:12px 14px;border-radius:11px;font-size:11px}.err{color:#B95C66;background:#F8ECEF}.note{color:#596079;background:#F3EFF9;border:1px solid #DCD6EE}@media(max-width:850px){.grid{grid-template-columns:1fr 1fr}}@media(max-width:640px){.wrap{padding:80px 14px 90px}.grid{grid-template-columns:1fr 1fr}.card{padding:14px}.card strong{font-size:21px}.actions{flex-direction:column}.actions .btn{width:100%}}"}</style><div className="wrap">
 <div className="ey">ARMAZENAMENTO</div><h1>Central de armazenamento</h1><p className="sub">Veja onde seu espaço está sendo usado e libere armazenamento excluindo galerias que não precisa mais manter.</p>
 {erro&&<div className="err">{erro}</div>}
 {dados&&<><section className="grid"><div className="card"><strong>{fmt(dados.usoBytes)}</strong><span>Em uso agora</span></div><div className="card"><strong>{dados.limiteGb==null?"Ilimitado":dados.limiteGb+" GB"}</strong><span>Limite do plano {dados.plano.nome}</span></div><div className="card"><strong>{ativas}</strong><span>Galerias ocupando espaço</span></div><div className="card"><strong>{fmt(dados.residualBytes)}</strong><span>Arquivos em limpeza residual</span></div></section>
 {limiteBytes&&<section className="panel meter"><div className="meter-head"><span>{fmt(dados.usoBytes)} de {dados.limiteGb} GB</span><strong>{pct}%</strong></div><div className="track"><i style={{width:pct+"%"}}/></div><div className="actions"><button className="btn primary" onClick={()=>router.push("/upload")}>Nova galeria</button><button className="btn" onClick={()=>router.push("/dashboard/assinatura")}>Ver planos</button></div></section>}
 {dados.residualBytes>0&&<div className="note">Há {fmt(dados.residualBytes)} em arquivos residuais sem galeria ativa. O Fotura remove esses arquivos automaticamente; eles continuam contabilizados até a limpeza terminar.</div>}
 <div className="table-wrap"><table className="table"><thead><tr><th>Galeria</th><th>Status</th><th>Armazenamento</th><th>Entrega final</th><th>Arquivos</th><th>Validade</th><th></th></tr></thead><tbody>{dados.galerias.map(g=><tr key={g.id}><td><div className="name">{g.titulo}</div><div className="muted">{g.criadoEm?new Date(g.criadoEm).toLocaleDateString("pt-BR"):"—"}</div></td><td><span className={"pill"+(g.etapa==="entrega"?" done":"")}>{g.etapa.replaceAll("_"," ")}</span></td><td>{fmt(g.bytesTotal)}</td><td>{fmt(g.bytesEntrega)}</td><td>{g.arquivosTotal}</td><td>{g.linkAte?<span className={"pill"+(g.expirada?" warn":"")}>{g.expirada?"expirada":"até "+new Date(g.linkAte+"T12:00:00").toLocaleDateString("pt-BR")}</span>:"—"}</td><td><button className="btn" disabled={apagando===g.id} onClick={()=>void excluir(g)}>{apagando===g.id?"Excluindo…":"Excluir"}</button></td></tr>)}</tbody></table></div></>}
 </div></div>
}
