"use client";

import { Suspense, useEffect, useMemo, useRef, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { createClient } from "../../lib/supabase-client";
import MenuFotografo from "../MenuFotografo";

type Cliente = { id:string; nome:string; email:string|null; telefone:string|null };

function gerarSlug(texto:string){return texto.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")}
function gerarMiniatura(arquivo:File,maxLado=600,qualidade=.7):Promise<Blob|null>{return new Promise(resolve=>{const img=new Image(),url=URL.createObjectURL(arquivo);img.onload=()=>{URL.revokeObjectURL(url);let l=img.naturalWidth,a=img.naturalHeight;const e=Math.min(1,maxLado/Math.max(l,a));l=Math.max(1,Math.round(l*e));a=Math.max(1,Math.round(a*e));const c=document.createElement("canvas");c.width=l;c.height=a;const x=c.getContext("2d");if(!x){resolve(null);return}x.drawImage(img,0,0,l,a);c.toBlob(b=>resolve(b),"image/jpeg",qualidade)};img.onerror=()=>{URL.revokeObjectURL(url);resolve(null)};img.src=url})}

function UploadContent(){
 const router=useRouter(),searchParams=useSearchParams(),supabase=useMemo(()=>createClient(),[]),inputRef=useRef<HTMLInputElement>(null);
 const galeriaFixa=searchParams.get("galeria"),nomeTravado=Boolean(galeriaFixa);
 const[carregando,setCarregando]=useState(true),[enviando,setEnviando]=useState(false),[mensagem,setMensagem]=useState(""),[erro,setErro]=useState(false),[arquivos,setArquivos]=useState<FileList|null>(null),[nomeGaleria,setNomeGaleria]=useState(""),[tituloTravado,setTituloTravado]=useState(""),[link,setLink]=useState("");
 const[clientes,setClientes]=useState<Cliente[]>([]),[clienteId,setClienteId]=useState(""),[novoCliente,setNovoCliente]=useState(false),[clienteNome,setClienteNome]=useState(""),[clienteEmail,setClienteEmail]=useState(""),[clienteTelefone,setClienteTelefone]=useState("");
 useEffect(()=>{let ativo=true;(async()=>{const{data}=await supabase.auth.getUser();if(!data.user){router.replace("/login");return}const uid=data.user.id;const{data:cs}=await supabase.from("clientes").select("id,nome,email,telefone").eq("user_id",uid).order("nome");if(ativo)setClientes((cs??[]) as Cliente[]);if(galeriaFixa){const{data:g}=await supabase.from("galerias").select("titulo,cliente_id").eq("id",galeriaFixa).eq("user_id",uid).maybeSingle();if(ativo){setTituloTravado(g?.titulo||"Galeria");setClienteId((g?.cliente_id as string|null)??"")}}if(ativo)setCarregando(false)})();return()=>{ativo=false}},[router,supabase,galeriaFixa]);
 async function enviarFotos(){setErro(false);setLink("");setMensagem("");if(!arquivos?.length){setErro(true);setMensagem("Escolha pelo menos uma foto.");return}const{data:u}=await supabase.auth.getUser();if(!u.user){router.replace("/login");return}const uid=u.user.id;let galeriaId=galeriaFixa;
  if(!galeriaId){const t=nomeGaleria.trim();if(!t){setErro(true);setMensagem("Dê um nome pra galeria.");return}const novoNome=novoCliente?clienteNome.trim():"";if(novoCliente&&!novoNome){setErro(true);setMensagem("Informe o nome do novo cliente.");return}const{data:nova,error:e}=await supabase.rpc("criar_galeria_transacional",{p_slug:gerarSlug(t),p_titulo:t,p_cliente_id:novoCliente?null:(clienteId||null),p_cliente_nome:novoCliente?novoNome:null,p_cliente_email:novoCliente?(clienteEmail.trim()||null):null,p_cliente_telefone:novoCliente?(clienteTelefone.trim()||null):null}).single();if(e||!nova){setErro(true);setMensagem("Não foi possível criar a galeria.");return}galeriaId=nova.galeria_id as string}
  setEnviando(true);let enviadas=0;const lista=Array.from(arquivos);for(let i=0;i<lista.length;i++){const arq=lista[i],nomeLimpo=arq.name.replace(/[^a-zA-Z0-9._-]/g,"_"),nome=`${Date.now()}-${i}-${nomeLimpo}`,caminho=`${uid}/${galeriaId}/${nome}`;const{error}=await supabase.storage.from("fotos").upload(caminho,arq);if(error){setErro(true);setMensagem(`Erro ao enviar ${arq.name}.`);setEnviando(false);return}const thumb=await gerarMiniatura(arq);if(thumb)await supabase.storage.from("fotos").upload(`${uid}/${galeriaId}/thumbs/${nome}`,thumb,{contentType:"image/jpeg"});enviadas++}setMensagem(`${enviadas} foto(s) enviada(s) com sucesso!`);setLink(`${window.location.origin}/g/${galeriaId}`);setEnviando(false)}
 async function copiarLink(){try{await navigator.clipboard.writeText(link);setErro(false);setMensagem("Link copiado!")}catch{setErro(true);setMensagem("Não consegui copiar — copie o link manualmente.")}}
 if(carregando)return <div className="loading">Carregando…<style>{`.loading{min-height:100vh;display:flex;align-items:center;justify-content:center;background:linear-gradient(180deg,#0b0b1a,#111126);color:#7a7f9a}`}</style></div>;
 const clienteAtual=clientes.find(c=>c.id===clienteId);
 return <div className="mf-shift up-page"><MenuFotografo/><style>{`.up-page{min-height:100vh;background:linear-gradient(180deg,#0b0b1a,#111126);display:flex;flex-direction:column}.up-wrap{flex:1;display:flex;align-items:center;justify-content:center;padding:24px}.up-card{background:#16162a;border-radius:16px;padding:40px;width:100%;max-width:500px;border:1px solid #2a2d40}.up-label{font-size:13px;color:#a0a4b8;display:block;margin:0 0 6px}.up-input,.up-select{width:100%;padding:12px 14px;font-size:14px;border:1.5px solid #2a2d40;border-radius:10px;background:#0f0f1a;color:#f0f0f5;outline:none;margin-bottom:16px;box-sizing:border-box}.up-client-head{display:flex;align-items:center;justify-content:space-between;gap:10px}.up-mini{border:0;background:none;color:#7ea2ff;font:600 12px inherit;cursor:pointer}.up-new{padding:14px;border:1px solid #292b43;border-radius:11px;background:#111124;margin-bottom:18px}.up-file{width:100%;display:flex;align-items:center;justify-content:center;gap:9px;padding:13px;font:600 14px inherit;color:#c3c7db;cursor:pointer;background:rgba(74,108,247,.06);border:1.5px dashed #34385a;border-radius:12px}.up-file-status{font-size:12px;color:#7a7f9a;text-align:center;margin:10px 0 24px}.up-file-status.tem{color:#8fe3b0}.up-enviar{width:100%;padding:15px;font:700 15px inherit;color:#fff;border:0;border-radius:12px;cursor:pointer;background:linear-gradient(90deg,#1196fc,#5d0dfa)}.up-enviar:disabled{opacity:.65;cursor:default}.up-note{font-size:11px;color:#666c86;margin:-8px 0 16px}.up-msg{font-size:13px;text-align:center;margin-top:16px}.up-link{margin-top:20px;padding:16px;background:#0f0f1a;border:1px solid #2a2d40;border-radius:10px}@media(max-width:640px){.up-wrap{padding:76px 14px 24px;align-items:flex-start}.up-card{padding:25px 20px}}`}</style><div className="up-wrap"><div className="up-card"><p style={{fontSize:18,fontWeight:600,color:"#f0f0f5",textAlign:"center",marginBottom:4}}>{nomeTravado?"Enviar mais fotos":"Nova galeria"}</p><p style={{fontSize:13,color:"#7a7f9a",textAlign:"center",marginBottom:28}}>{nomeTravado?tituloTravado:"Dê um nome, vincule o cliente e escolha as fotos"}</p><label className="up-label">Nome da galeria</label><input className="up-input" value={nomeTravado?tituloTravado:nomeGaleria} onChange={e=>setNomeGaleria(e.target.value)} disabled={nomeTravado} placeholder="Ex: Casamento Ana e João"/>
 {!nomeTravado&&<><div className="up-client-head"><label className="up-label">Cliente <span style={{color:"#666c86"}}>(opcional)</span></label><button className="up-mini" type="button" onClick={()=>setNovoCliente(v=>!v)}>{novoCliente?"Usar existente":"+ Cadastrar agora"}</button></div>{!novoCliente?<select className="up-select" value={clienteId} onChange={e=>setClienteId(e.target.value)}><option value="">Sem cliente vinculado</option>{clientes.map(c=><option value={c.id} key={c.id}>{c.nome}{c.email?` — ${c.email}`:""}</option>)}</select>:<div className="up-new"><label className="up-label">Nome do cliente</label><input className="up-input" value={clienteNome} onChange={e=>setClienteNome(e.target.value)} placeholder="Nome"/><label className="up-label">E-mail</label><input className="up-input" type="email" value={clienteEmail} onChange={e=>setClienteEmail(e.target.value)} placeholder="opcional"/><label className="up-label">Telefone</label><input className="up-input" value={clienteTelefone} onChange={e=>setClienteTelefone(e.target.value)} placeholder="opcional"/></div>}<p className="up-note">O cliente não precisa informar esses dados ao abrir a galeria. O vínculo é apenas para sua organização interna.</p></>}
 {nomeTravado&&clienteAtual&&<p className="up-note">Cliente vinculado: <strong style={{color:"#aeb5d2"}}>{clienteAtual.nome}</strong></p>}<label className="up-label">Fotos</label><input ref={inputRef} type="file" accept="image/*" multiple onChange={e=>setArquivos(e.target.files)} style={{display:"none"}}/><button type="button" className="up-file" onClick={()=>inputRef.current?.click()}>Escolher fotos</button><p className={"up-file-status"+(arquivos?.length?" tem":"")}>{arquivos?.length?`${arquivos.length} foto${arquivos.length===1?"":"s"} selecionada${arquivos.length===1?"":"s"}`:"Nenhuma foto selecionada"}</p><button className="up-enviar" onClick={enviarFotos} disabled={enviando}>{enviando?"Enviando…":nomeTravado?"Enviar fotos":"Criar nova galeria"}</button>{mensagem&&<p className="up-msg" style={{color:erro?"#ff9d9d":"#8fe3b0"}}>{mensagem}</p>}{link&&<div className="up-link"><p style={{fontSize:12,color:"#7a7f9a"}}>Link para enviar ao cliente:</p><p style={{fontSize:13,color:"#7ea2ff",wordBreak:"break-all"}}>{link}</p><button className="up-file" onClick={copiarLink}>Copiar link</button></div>}</div></div></div>}

export default function UploadPage(){return <Suspense fallback={<div/>}><UploadContent/></Suspense>}
