"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "../../../lib/supabase-client";
import MenuFotografo from "../../MenuFotografo";

type Cliente = { id:string; nome:string; email:string|null; telefone:string|null; criado_em:string };
type Galeria = { id:string; titulo:string; cliente_id:string|null; criado_em:string; prova:boolean };
type Selecao = { galeria:string; finalizada:boolean; atualizado_em:string|null };

export default function ClientesPage(){
 const router=useRouter(); const supabase=useMemo(()=>createClient(),[]);
 const [uid,setUid]=useState(""); const [clientes,setClientes]=useState<Cliente[]>([]); const [galerias,setGalerias]=useState<Galeria[]>([]); const [selecoes,setSelecoes]=useState<Record<string,Selecao>>({});
 const [carregando,setCarregando]=useState(true); const [busca,setBusca]=useState(""); const [aviso,setAviso]=useState(""); const [editando,setEditando]=useState<string|null>(null);
 const [nome,setNome]=useState(""); const [email,setEmail]=useState(""); const [telefone,setTelefone]=useState("");
 useEffect(()=>{let ativo=true;(async()=>{const {data:a}=await supabase.auth.getUser(); if(!a.user){router.replace("/login");return} setUid(a.user.id);
  const [{data:c,error},{data:g}]=await Promise.all([supabase.from("clientes").select("id,nome,email,telefone,criado_em").eq("user_id",a.user.id).order("nome"),supabase.from("galerias").select("id,titulo,cliente_id,criado_em,prova").eq("user_id",a.user.id).order("criado_em",{ascending:false})]);
  if(!ativo)return; if(error){setAviso("Não foi possível carregar seus clientes agora.");setCarregando(false);return} const gs=(g??[]) as Galeria[]; setClientes((c??[]) as Cliente[]);setGalerias(gs);
  const ids=gs.map(x=>x.id); if(ids.length){const {data:s}=await supabase.from("selecoes").select("galeria,finalizada,atualizado_em").in("galeria",ids); const m:Record<string,Selecao>={}; for(const x of s??[])m[x.galeria]=x as Selecao;setSelecoes(m)} setCarregando(false);
 })();return()=>{ativo=false}},[router,supabase]);
 const filtrados=useMemo(()=>{const q=busca.trim().toLowerCase();return clientes.filter(c=>!q||c.nome.toLowerCase().includes(q)||(c.email??"").toLowerCase().includes(q)||(c.telefone??"").includes(q))},[clientes,busca]);
 function limpar(){setEditando(null);setNome("");setEmail("");setTelefone("")}
 function editar(c:Cliente){setEditando(c.id);setNome(c.nome);setEmail(c.email??"");setTelefone(c.telefone??"")}
 async function salvar(e:FormEvent){e.preventDefault();if(!nome.trim())return; const dados={user_id:uid,nome:nome.trim(),email:email.trim()||null,telefone:telefone.trim()||null};
  if(editando){const {data,error}=await supabase.from("clientes").update(dados).eq("id",editando).eq("user_id",uid).select("id,nome,email,telefone,criado_em").single();if(error){setAviso("Não foi possível atualizar o cliente.");return}setClientes(p=>p.map(c=>c.id===editando?data as Cliente:c));setAviso("Cliente atualizado.")}
  else {const {data,error}=await supabase.from("clientes").insert(dados).select("id,nome,email,telefone,criado_em").single();if(error){setAviso("Não foi possível cadastrar o cliente.");return}setClientes(p=>[...p,data as Cliente].sort((a,b)=>a.nome.localeCompare(b.nome,"pt-BR")));setAviso("Cliente cadastrado.")} limpar(); }
 async function excluir(c:Cliente){if(!confirm(`Excluir ${c.nome}? As galerias continuarão existindo, apenas sem vínculo com este cliente.`))return;const {error}=await supabase.from("clientes").delete().eq("id",c.id).eq("user_id",uid);if(error){setAviso("Não foi possível excluir o cliente.");return}setClientes(p=>p.filter(x=>x.id!==c.id));setGalerias(p=>p.map(g=>g.cliente_id===c.id?{...g,cliente_id:null}:g));setAviso("Cliente excluído.")}
 function status(g:Galeria){const s=selecoes[g.id];if(!g.prova)return"Entrega";if(!s)return"Aguardando";return s.finalizada?"Finalizada":"Em andamento"}
 return <main className="dash mf-shift"><MenuFotografo/><style>{`
 .dash{min-height:100vh;background:linear-gradient(180deg,#0b0b1a 0%,#101024 100%);color:#f0f0f5;padding-top:46px;padding-right:5vw;padding-bottom:80px;box-sizing:border-box}.wrap{max-width:1180px;margin:auto}.top{display:flex;justify-content:space-between;gap:18px;align-items:end;margin-bottom:26px}.ey{font-size:11px;letter-spacing:2px;color:#6f76a0}.h1{font-size:28px;margin:7px 0 0}.sub{color:#7a7f9a;font-size:13px}.grid{display:grid;grid-template-columns:340px 1fr;gap:18px}.card{background:linear-gradient(180deg,#14142b,#101023);border:1px solid #23233c;border-radius:16px;padding:20px}.input{width:100%;box-sizing:border-box;background:#0d0d1e;border:1px solid #292b43;border-radius:10px;padding:11px 12px;color:#f0f0f5;font:inherit;margin:6px 0}.btn{border:0;border-radius:10px;padding:10px 14px;color:white;font:inherit;font-weight:600;cursor:pointer;background:linear-gradient(90deg,#1196fc,#5d0dfa)}.ghost{background:#17172d;border:1px solid #292b43;color:#aeb2c8}.danger{color:#ff9d9d}.row{padding:16px 0;border-bottom:1px solid #202238}.row:last-child{border:0}.rhead{display:flex;justify-content:space-between;gap:12px}.name{font-weight:650}.meta{font-size:12px;color:#7a7f9a;margin-top:4px}.gals{display:flex;flex-wrap:wrap;gap:7px;margin-top:10px}.pill{font-size:11px;border:1px solid #2a2d45;border-radius:999px;padding:5px 8px;color:#9da2bc}.actions{display:flex;gap:7px;margin-top:11px}.notice{margin-bottom:16px;color:#8fe3b0;font-size:13px}.empty{padding:40px 10px;text-align:center;color:#7a7f9a}.search{max-width:320px}@media(max-width:900px){.grid{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}.search{max-width:none;width:100%}}@media(max-width:640px){.dash{padding:76px 18px 60px}.h1{font-size:24px}}
 `}</style><div className="wrap"><header className="top"><div><div className="ey">CLIENTES</div><h1 className="h1">Seus clientes</h1><p className="sub">Organize contatos e acompanhe as galerias vinculadas a cada pessoa.</p></div><input className="input search" placeholder="Buscar cliente" value={busca} onChange={e=>setBusca(e.target.value)}/></header>{aviso&&<div className="notice">{aviso}</div>}<div className="grid"><form className="card" onSubmit={salvar}><h2 style={{fontSize:16,marginTop:0}}>{editando?"Editar cliente":"Novo cliente"}</h2><label className="sub">Nome<input className="input" value={nome} onChange={e=>setNome(e.target.value)} required/></label><label className="sub">E-mail<input className="input" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="sub">Telefone<input className="input" value={telefone} onChange={e=>setTelefone(e.target.value)}/></label><div className="actions"><button className="btn" type="submit">{editando?"Salvar":"Cadastrar"}</button>{editando&&<button className="btn ghost" type="button" onClick={limpar}>Cancelar</button>}</div></form><section className="card">{carregando?<div className="empty">Carregando clientes…</div>:filtrados.length===0?<div className="empty">{clientes.length?"Nenhum cliente encontrado.":"Você ainda não cadastrou clientes."}</div>:filtrados.map(c=>{const gs=galerias.filter(g=>g.cliente_id===c.id);return <article className="row" key={c.id}><div className="rhead"><div><div className="name">{c.nome}</div><div className="meta">{[c.email,c.telefone].filter(Boolean).join(" · ")||"Sem contato informado"}</div></div><div className="meta">{gs.length} {gs.length===1?"galeria":"galerias"}</div></div>{gs.length>0&&<div className="gals">{gs.slice(0,4).map(g=><span className="pill" key={g.id}>{g.titulo} · {status(g)}</span>)}</div>}<div className="actions"><button className="btn ghost" onClick={()=>editar(c)}>Editar</button><button className="btn ghost danger" onClick={()=>excluir(c)}>Excluir</button></div></article>})}</section></div></div></main>
}
